package jwt

const (
	ACTIVITY_LOGGER = "jwt-activity"
	ACTIVITY_LOGGER_SIGN = "jwt-activity-sign"
	ACTIVITY_LOGGER_VERIFY = "jwt-activity-verify"
	ACTIVITY_LOGGER_DECODE_ONLY = "jwt-activity-decodeonly"
)

const (
	MODE_SIGN = "Sign"
	MODE_VERIFY = "Verify"
	MODE_DECODE_ONLY = "DecodeOnly"
)

const (
	SIGNING_METHOD_ES256 = "ES256"
	SIGNING_METHOD_ES384 = "ES384"
	SIGNING_METHOD_ES512 = "ES512"
	SIGNING_METHOD_EdDSA = "EdDSA"
	SIGNING_METHOD_HS256 = "HS256"
	SIGNING_METHOD_HS384 = "HS384"
	SIGNING_METHOD_HS512 = "HS512"
	SIGNING_METHOD_PS256 = "PS256"
	SIGNING_METHOD_PS384 = "PS384"
	SIGNING_METHOD_PS512 = "PS512"
	SIGNING_METHOD_RS256 = "RS256"
	SIGNING_METHOD_RS384 = "RS384"
	SIGNING_METHOD_RS512 = "RS512"
	SIGNING_METHOD_NONE = "none"
)